### ISSUE TITLE
use relative paths

### ISSUE THREAD

**Issue by rimmesbe** [thrisalagopu/prj-rev-bwfs-dasmoto#1]
Always use a relative path for link tags and img tags (the path from one file to the other). Right now you are using a root path, which will only work on your local computer.
relative path: "./resources/style.css"

https://github.com/thrisalagopu/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's/index.html#L6

**Comment by thrisalagopu** [comment]
Thank you Ryan. Shall use relative path going forward.
