### ISSUE TITLE
html sections

### ISSUE THREAD

**Issue by rimmesbe** [thrisalagopu/prj-rev-bwfs-dasmoto#2]
Right now you basically have one giant block of html which can be hard to read and understand. What we want to do is create sections in the html by wrapping related elements in divs.
<img width="122" alt="screen shot 2017-06-28 at 1 57 34 pm" src="https://user-images.githubusercontent.com/9957628/33849018-5cd38028-de7d-11e7-857f-3c2af98bf60e.png">
This will help with organization and styling.

https://github.com/thrisalagopu/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's/index.html#L10-L14

**Comment by thrisalagopu** [comment]
Thank you Ryan. Shall work on sectioning the code.
