### ISSUE TITLE
header tags bold

### ISSUE THREAD

**Issue by rimmesbe** [thrisalagopu/prj-rev-bwfs-dasmoto#3]
Header tags default to bold, so no need to add it. Also you can swap the span tags out for `<strong>` tags which also default to bold and work just like spans.

https://github.com/thrisalagopu/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's/resources/style.css#L5-L7

**Comment by thrisalagopu** [comment]
Thank you Ryan. I shall remember to use <strong>. Also I didn't know header tags default to bold. Learnt a new thing. Thank you again.
