### ISSUE TITLE
use class here

### ISSUE THREAD

**Issue by rimmesbe** [thrisalagopu/prj-rev-bwfs-dasmoto#4]
This would be a good place to add a class. We don't want to alter the default styling of the span tag since they may need to be used elsewhere without the added styling. A class lets us preserve that default styling and add some semantic description to the component being styled:
.price { color: blue; }

https://github.com/thrisalagopu/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's/resources/style.css#L27-L29

**Comment by thrisalagopu** [comment]
Got it. Thank you Ryan.
