### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [thrisalagopu/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on the project, the site looks good. You used some good techniques here and had good instincts. Take a look at the issues I created as they will introduce some new concepts and techniques you should start using. Here is a good article with some examples as well: 
http://learn.shayhowe.com/html-css/writing-your-best-code/

**Comment by thrisalagopu** [comment]
Thank you very much for the comments Ryan. I learnt a bunch of things from your review. I shall keep them all in mind and put them to use in my future projects. 

Apologies for the delayed response for the review. I didn't know that I should close the issues.

Thank you again for your time. :)
